name: Generate Metrics
on:
  schedule:
    - cron: "0 * * * *" # Запуск раз в час
  workflow_dispatch: # Для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: header, activity, repositories
